name: Check Planet Cinema

on:
  schedule:
    - cron: "8,33,48 * * * *"
  workflow_dispatch:

jobs:
  check-cinema:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: echo "GitHub Actions scheduler is working!"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install requests

      - name: Check cinema
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python check_cinema.py
